#!/usr/bin/env python3
"""Sign an Android A/B OTA payload.bin with RSA-2048 key.

Adds metadata and payload signatures to an unsigned payload.bin
generated by payload_packer. Patches the manifest protobuf to include
signatures_offset and signatures_size fields.

Payload format (CrAU):
  - Magic: "CrAU" (4 bytes)
  - Version: uint64 big-endian (8 bytes) = 2
  - Manifest size: uint64 big-endian (8 bytes)
  - Metadata signature size: uint32 big-endian (4 bytes)
  - Manifest (protobuf DeltaArchiveManifest)
  - Metadata signatures (protobuf Signatures)
  - Blob data
  - Payload signatures (protobuf Signatures)
"""

import struct
import hashlib
import subprocess
import sys
import os
import tempfile
import base64

HEADER_SIZE = 24  # 4 + 8 + 8 + 4


def sign_hash(hash_bytes, private_key_pem):
    """Sign a SHA-256 hash with RSA private key using PKCS1 v1.5."""
    with tempfile.NamedTemporaryFile(delete=False) as f:
        f.write(hash_bytes)
        hash_file = f.name
    with tempfile.NamedTemporaryFile(delete=False) as f:
        sig_file = f.name
    try:
        subprocess.run([
            'openssl', 'pkeyutl', '-sign',
            '-inkey', private_key_pem,
            '-in', hash_file,
            '-out', sig_file,
            '-pkeyopt', 'digest:sha256'
        ], check=True, capture_output=True)
        with open(sig_file, 'rb') as f:
            return f.read()
    finally:
        os.unlink(hash_file)
        os.unlink(sig_file)


def build_signatures_proto(signature_bytes):
    """Build a Signatures protobuf message."""
    # Signature.data (field 2, wire type 2)
    sig_data = b'\x12' + encode_varint(len(signature_bytes)) + signature_bytes
    # Signatures.signatures (field 1, wire type 2)
    return b'\x0a' + encode_varint(len(sig_data)) + sig_data


def encode_varint(value):
    """Encode an integer as a protobuf varint."""
    result = b''
    while value > 0x7f:
        result += bytes([(value & 0x7f) | 0x80])
        value >>= 7
    result += bytes([value & 0x7f])
    return result


def patch_manifest(manifest_bytes, signatures_offset, signatures_size,
                    max_timestamp=None, minor_version=None):
    """Append signatures_offset, signatures_size, max_timestamp, and
    optionally fix minor_version in the manifest.

    DeltaArchiveManifest:
      optional uint64 signatures_offset = 4;
      optional uint64 signatures_size = 5;
      optional uint32 minor_version = 12;
      optional int64 max_timestamp = 14;
    """
    # field 4, wire type 0 (varint): tag = (4 << 3) | 0 = 0x20
    field4 = b'\x20' + encode_varint(signatures_offset)
    # field 5, wire type 0 (varint): tag = (5 << 3) | 0 = 0x28
    field5 = b'\x28' + encode_varint(signatures_size)
    result = manifest_bytes + field4 + field5
    if minor_version is not None:
        # field 12, wire type 0 (varint): tag = (12 << 3) | 0 = 0x60
        # This overwrites field 12 if it already exists (protobuf last-write-wins)
        result += b'\x60' + encode_varint(minor_version)
    if max_timestamp is not None:
        # field 14, wire type 0 (varint): tag = (14 << 3) | 0 = 0x70
        result += b'\x70' + encode_varint(max_timestamp)
    return result


def sign_payload(input_path, output_path, private_key_pem):
    with open(input_path, 'rb') as f:
        data = f.read()

    magic = data[0:4]
    if magic != b'CrAU':
        print(f"Error: not a CrAU payload (magic: {magic})")
        sys.exit(1)

    version = struct.unpack('>Q', data[4:12])[0]
    manifest_size = struct.unpack('>Q', data[12:20])[0]
    metadata_sig_size = struct.unpack('>I', data[20:24])[0]

    print(f"Version: {version}")
    print(f"Manifest size: {manifest_size}")
    print(f"Current metadata sig size: {metadata_sig_size}")

    manifest = data[HEADER_SIZE:HEADER_SIZE + manifest_size]
    blob_data = data[HEADER_SIZE + manifest_size + metadata_sig_size:]

    print(f"Blob data size: {len(blob_data)}")

    # RSA-2048 signature is always 256 bytes, proto wrapping adds 6 bytes
    # Pre-compute the signatures proto size
    dummy_sig = b'\x00' * 256
    sig_proto_size = len(build_signatures_proto(dummy_sig))
    print(f"Signature proto size: {sig_proto_size}")

    # Patch manifest with signatures_offset, signatures_size, and max_timestamp
    # signatures_offset = offset from end of metadata (header+manifest+metasig) to payload sig
    # = size of blob data
    # max_timestamp must be >= device's ro.build.date.utc or update is rejected
    import time
    max_ts = int(time.time()) + 86400  # now + 1 day

    # Delta payloads with SOURCE_COPY ops require minor_version >= 2
    # Full payloads must have minor_version = 0
    # Android 9 supports up to minor_version 4
    is_delta = '--delta' in sys.argv
    minor_ver = 4 if is_delta else None
    if is_delta:
        print("Delta mode - setting minor_version=4")

    patched_manifest = patch_manifest(manifest, len(blob_data), sig_proto_size,
                                      max_ts, minor_ver)
    print(f"Patched manifest size: {len(patched_manifest)}")

    # Build header + manifest (metadata for signing)
    new_header = (
        b'CrAU'
        + struct.pack('>Q', version)
        + struct.pack('>Q', len(patched_manifest))
        + struct.pack('>I', 0)  # placeholder for metadata_sig_size
    )
    metadata = new_header + patched_manifest

    # Sign metadata
    print("Signing metadata...")
    metadata_hash = hashlib.sha256(metadata).digest()
    metadata_sig = sign_hash(metadata_hash, private_key_pem)
    metadata_sig_proto = build_signatures_proto(metadata_sig)

    # Update header with actual metadata_sig_size
    new_header = (
        b'CrAU'
        + struct.pack('>Q', version)
        + struct.pack('>Q', len(patched_manifest))
        + struct.pack('>I', len(metadata_sig_proto))
    )

    # Re-sign metadata with correct header (sig size now set)
    metadata = new_header + patched_manifest
    metadata_hash = hashlib.sha256(metadata).digest()
    metadata_sig = sign_hash(metadata_hash, private_key_pem)
    metadata_sig_proto = build_signatures_proto(metadata_sig)

    # Build full payload (header + manifest + metadata_sig + blob + payload_sig)
    # IMPORTANT: update_engine hashes header+manifest+blob, EXCLUDING metadata sig
    payload_for_hash = new_header + patched_manifest + blob_data

    # Sign the payload hash (what update_engine will compute)
    print("Signing payload...")
    payload_hash = hashlib.sha256(payload_for_hash).digest()
    payload_sig = sign_hash(payload_hash, private_key_pem)
    payload_sig_proto = build_signatures_proto(payload_sig)

    # Final payload includes everything
    final_payload = new_header + patched_manifest + metadata_sig_proto + blob_data + payload_sig_proto

    with open(output_path, 'wb') as f:
        f.write(final_payload)

    print(f"\nSigned payload: {output_path} ({len(final_payload)} bytes)")
    print(f"  Manifest: {len(patched_manifest)} bytes")
    print(f"  Metadata sig: {len(metadata_sig_proto)} bytes")
    print(f"  Blob data: {len(blob_data)} bytes")
    print(f"  Payload sig: {len(payload_sig_proto)} bytes")

    # Write payload_properties.txt
    props_path = os.path.join(os.path.dirname(output_path), 'payload_properties.txt')
    file_hash = base64.b64encode(hashlib.sha256(final_payload).digest()).decode()
    meta_hash = base64.b64encode(hashlib.sha256(metadata).digest()).decode()
    metadata_size = HEADER_SIZE + len(patched_manifest)

    props = (
        f"FILE_HASH={file_hash}\n"
        f"FILE_SIZE={len(final_payload)}\n"
        f"METADATA_HASH={meta_hash}\n"
        f"METADATA_SIZE={metadata_size}\n"
    )
    with open(props_path, 'w') as f:
        f.write(props)
    print(f"Updated: {props_path}")


if __name__ == '__main__':
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <unsigned_payload.bin> <signed_payload.bin> <private_key.pem>")
        sys.exit(1)
    sign_payload(sys.argv[1], sys.argv[2], sys.argv[3])
